## 2.1 Promise 是什么？

2.1.1. 理解
①Promise 是 JS 中进行异步编程的新解决方案
② Promise 是一个构造函数

## 异步编程

- fs 文件操作
- 数据库操作
- AJAX
- 定时器

## 2.2.1.指定回调函数的方式更加灵活

2.2.2. 支持链式调用，可以解决回调地狱问题  
1.回调地狱：回调函数嵌套使用，外部回调函数异步执行的结果是嵌套的回调执行的条件
缺点是：不便于阅读，不便于异常处理

## Promise 的状态

实例对象中的一个属性：「PromiseState」

- pending 未决定的
- resolved /fulfilled 成功
- rejected 失败
- 变换有两种，只能改变一次

## Promise 对象的值

实例对象中的一个属性：「PromiseResult」
保存着对象成功或失败的结果

- resolve
- reject

## Promise 的 API

- Promise 实例的 then() 方法最多接受两个参数：用于 Promise 兑现和拒绝情况的回调函数。
  它立即返回一个等效的 Promise 对象，允许你链接到其他 Promise 方法，从而实现链式调用。

- Promise.all() 静态方法接受一个 Promise 可迭代对象作为输入，并返回一个 Promise。
  当所有输入的 Promise 都被兑现时，返回的 Promise 也将被兑现（即使传入的是一个空的可迭代对象），并返回一个包含所有兑现值的数组。
  如果输入的任何 Promise 被拒绝，则返回的 Promise 将被拒绝，并带有第一个被拒绝的原因。

- Promise.reject() 静态方法返回一个已拒绝（rejected）的 Promise 对象，拒绝原因为给定的参数。

- Promise.resolve() 静态方法将给定的值转换为一个 Promise。
  如果该值本身就是一个 Promise，那么该 Promise 将被返回；
  如果该值是一个 thenable 对象，Promise.resolve() 将调用其 then() 方法及其两个回调函数；
  否则，返回的 Promise 将会以该值兑现。

## Promise 的几个关键问题

- 改变状态
- 一个 Promise 指定多个成功/失败的回调函数，都会调用吗？ 是的

* .then()返回新的 Promise 的结果状态由什么决定
  ① 如果抛出异常，新 promise 变为 rejected,reason 为抛出的异常；
  ② 如果返回的是非 promise 的任意值，新 promise 变为 resolved,value 为返回的值
  ③ 如果返回的是另一个新 promise,此 promise 的结果就会成为新 promise 的结果

* 如何串联多个任务
  ① promise 的 then()返回一个新的 promise,可以开成 then()的链式调用
  ② 通过 then 的链式调用串联多个同步/异步任务

* promise 异常穿透

# 自定义（手写）Promise

## 定义整体结构

- try 和 catch 是用于处理异常的语句，它们构成了一种异常处理机制。在一个 try 语句中，程序执行一段代码，如果发生了异常，则会被捕获，并转到相应的 catch 语句中进行处理。

## async 函数

- 函数的返回值为 promise 对象
- promise 对象的结果由 async 函数执行的返回值决定

## await 表达式

- await 右侧的表达式一般为 promise 对象，但也可以是其它的值
